version: "3.9"

services:
  app:
    build: .
    container_name: ues_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: ues_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ues_egresados
      MYSQL_USER: ues_user
      MYSQL_PASSWORD: ues_pass
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ues_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
